# GitHub Actions para Build e Deploy da API Java para Azure Web App - DEV
name: Build and deploy JAR app to Azure Web App - todo-list-dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Necessário para ações de checkout

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build com Maven
        run: mvn clean package -DskipTests
        working-directory: todo-list


      - name: Upload do Artefato para o Job de Deploy
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'todo-list/target/*.jar'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixar Artefato do Job de Build
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: todo-list


      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy para Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'todo-list-dev'
          package: '*.jar'

