# GitHub Actions for Build and Deploy of the Java API to Azure Web App - TST
name: Build and deploy JAR app to Azure Web App - todo-list-tst

on:
  push:
    branches:
      - tst
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for checkout actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: todo-list

      - name: Upload Artifact for Deploy Job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'todo-list/target/*.jar'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'testing'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: todo-list


      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'todo-list-tst'
          package: '*.jar'
